- name: Download Tomcat using get_url
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz
    dest: /home/ubuntu/apache-tomcat-9.0.71.tar.gz
    force_basic_auth: yes 

- name: i want folder
  file: 
    path: /opt/tomcat/
    state: directory 

- name: i want to extract tar file 
  command: 
      cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-9.0.71.tar.gz -C /opt/tomcat --strip-components=1
      creates: /opt/tomcat/LICENCE